name: Build and Test Math Library
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  buildandtest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    # Install .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    # Install project dependencies
    - name: Install dependencies
      run: dotnet restore
    
    # Build solution
    - name: Build
      run: dotnet build --configuration Release --no-restore src/MathLib
    
    # Run unit tests
    - name: Execute Unit Tests
      run: dotnet test --no-restore --verbosity normal src/MathLibTests
