name: Build and Test Math Library
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildandtest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Install .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Build solution
    - name: Build
      run: dotnet build --configuration Release src/MathLib

    # Run unit tests
    - name: Execute Unit Tests
      run: dotnet test --verbosity normal src/MathLibTests
